services:

  __APP_NAME__-api:
    container_name: __APP_NAME__-api
    build: .
    privileged: true
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DB_HOST=__APP_NAME__-database
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - __APP_NAME__-database
    networks:
      - network

  __APP_NAME__-database:
    container_name: __APP_NAME__-database
    image: postgres
    volumes:
      - /var/lib/postgres/data
    env_file: .env
    ports:
      - "5431:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - network

networks:
  network:
    name: network
    driver: bridge
